// Code generated by "enumer -type=TagSet -transform=snake -output tagset_gen.go"; DO NOT EDIT.

//
package tagset

import (
	"fmt"
)

const _TagSetName = "protosub_protostatusmethodurlnamegroupcheckerrorerror_codetls_versionitervuocsp_statusip"

var _TagSetMap = map[TagSet]string***REMOVED***
	1:     _TagSetName[0:5],
	2:     _TagSetName[5:14],
	4:     _TagSetName[14:20],
	8:     _TagSetName[20:26],
	16:    _TagSetName[26:29],
	32:    _TagSetName[29:33],
	64:    _TagSetName[33:38],
	128:   _TagSetName[38:43],
	256:   _TagSetName[43:48],
	512:   _TagSetName[48:58],
	1024:  _TagSetName[58:69],
	2048:  _TagSetName[69:73],
	4096:  _TagSetName[73:75],
	8192:  _TagSetName[75:86],
	16384: _TagSetName[86:88],
***REMOVED***

func (i TagSet) String() string ***REMOVED***
	if str, ok := _TagSetMap[i]; ok ***REMOVED***
		return str
	***REMOVED***
	return fmt.Sprintf("TagSet(%d)", i)
***REMOVED***

var _TagSetValues = []TagSet***REMOVED***1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384***REMOVED***

var _TagSetNameToValueMap = map[string]TagSet***REMOVED***
	_TagSetName[0:5]:   1,
	_TagSetName[5:14]:  2,
	_TagSetName[14:20]: 4,
	_TagSetName[20:26]: 8,
	_TagSetName[26:29]: 16,
	_TagSetName[29:33]: 32,
	_TagSetName[33:38]: 64,
	_TagSetName[38:43]: 128,
	_TagSetName[43:48]: 256,
	_TagSetName[48:58]: 512,
	_TagSetName[58:69]: 1024,
	_TagSetName[69:73]: 2048,
	_TagSetName[73:75]: 4096,
	_TagSetName[75:86]: 8192,
	_TagSetName[86:88]: 16384,
***REMOVED***

// TagSetString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TagSetString(s string) (TagSet, error) ***REMOVED***
	if val, ok := _TagSetNameToValueMap[s]; ok ***REMOVED***
		return val, nil
	***REMOVED***
	return 0, fmt.Errorf("%s does not belong to TagSet values", s)
***REMOVED***

// TagSetValues returns all values of the enum
func TagSetValues() []TagSet ***REMOVED***
	return _TagSetValues
***REMOVED***

// IsATagSet returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TagSet) IsATagSet() bool ***REMOVED***
	_, ok := _TagSetMap[i]
	return ok
***REMOVED***
