// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: route_guide.proto

package main

import (
	context "context"
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Points are represented as latitude-longitude pairs in the E7 representation
// (degrees multiplied by 10**7 and rounded to the nearest integer).
// Latitudes should be in the range +/- 90 degrees and longitude should be in
// the range +/- 180 degrees (inclusive).
type Point struct ***REMOVED***
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  int32 `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude int32 `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
***REMOVED***

func (x *Point) Reset() ***REMOVED***
	*x = Point***REMOVED******REMOVED***
	if protoimpl.UnsafeEnabled ***REMOVED***
		mi := &file_route_guide_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	***REMOVED***
***REMOVED***

func (x *Point) String() string ***REMOVED***
	return protoimpl.X.MessageStringOf(x)
***REMOVED***

func (*Point) ProtoMessage() ***REMOVED******REMOVED***

func (x *Point) ProtoReflect() protoreflect.Message ***REMOVED***
	mi := &file_route_guide_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil ***REMOVED***
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil ***REMOVED***
			ms.StoreMessageInfo(mi)
		***REMOVED***
		return ms
	***REMOVED***
	return mi.MessageOf(x)
***REMOVED***

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) ***REMOVED***
	return file_route_guide_proto_rawDescGZIP(), []int***REMOVED***0***REMOVED***
***REMOVED***

func (x *Point) GetLatitude() int32 ***REMOVED***
	if x != nil ***REMOVED***
		return x.Latitude
	***REMOVED***
	return 0
***REMOVED***

func (x *Point) GetLongitude() int32 ***REMOVED***
	if x != nil ***REMOVED***
		return x.Longitude
	***REMOVED***
	return 0
***REMOVED***

// A latitude-longitude rectangle, represented as two diagonally opposite
// points "lo" and "hi".
type Rectangle struct ***REMOVED***
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// One corner of the rectangle.
	Lo *Point `protobuf:"bytes,1,opt,name=lo,proto3" json:"lo,omitempty"`
	// The other corner of the rectangle.
	Hi *Point `protobuf:"bytes,2,opt,name=hi,proto3" json:"hi,omitempty"`
***REMOVED***

func (x *Rectangle) Reset() ***REMOVED***
	*x = Rectangle***REMOVED******REMOVED***
	if protoimpl.UnsafeEnabled ***REMOVED***
		mi := &file_route_guide_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	***REMOVED***
***REMOVED***

func (x *Rectangle) String() string ***REMOVED***
	return protoimpl.X.MessageStringOf(x)
***REMOVED***

func (*Rectangle) ProtoMessage() ***REMOVED******REMOVED***

func (x *Rectangle) ProtoReflect() protoreflect.Message ***REMOVED***
	mi := &file_route_guide_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil ***REMOVED***
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil ***REMOVED***
			ms.StoreMessageInfo(mi)
		***REMOVED***
		return ms
	***REMOVED***
	return mi.MessageOf(x)
***REMOVED***

// Deprecated: Use Rectangle.ProtoReflect.Descriptor instead.
func (*Rectangle) Descriptor() ([]byte, []int) ***REMOVED***
	return file_route_guide_proto_rawDescGZIP(), []int***REMOVED***1***REMOVED***
***REMOVED***

func (x *Rectangle) GetLo() *Point ***REMOVED***
	if x != nil ***REMOVED***
		return x.Lo
	***REMOVED***
	return nil
***REMOVED***

func (x *Rectangle) GetHi() *Point ***REMOVED***
	if x != nil ***REMOVED***
		return x.Hi
	***REMOVED***
	return nil
***REMOVED***

// A feature names something at a given point.
//
// If a feature could not be named, the name is empty.
type Feature struct ***REMOVED***
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the feature.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The point where the feature is detected.
	Location *Point `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
***REMOVED***

func (x *Feature) Reset() ***REMOVED***
	*x = Feature***REMOVED******REMOVED***
	if protoimpl.UnsafeEnabled ***REMOVED***
		mi := &file_route_guide_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	***REMOVED***
***REMOVED***

func (x *Feature) String() string ***REMOVED***
	return protoimpl.X.MessageStringOf(x)
***REMOVED***

func (*Feature) ProtoMessage() ***REMOVED******REMOVED***

func (x *Feature) ProtoReflect() protoreflect.Message ***REMOVED***
	mi := &file_route_guide_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil ***REMOVED***
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil ***REMOVED***
			ms.StoreMessageInfo(mi)
		***REMOVED***
		return ms
	***REMOVED***
	return mi.MessageOf(x)
***REMOVED***

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) ***REMOVED***
	return file_route_guide_proto_rawDescGZIP(), []int***REMOVED***2***REMOVED***
***REMOVED***

func (x *Feature) GetName() string ***REMOVED***
	if x != nil ***REMOVED***
		return x.Name
	***REMOVED***
	return ""
***REMOVED***

func (x *Feature) GetLocation() *Point ***REMOVED***
	if x != nil ***REMOVED***
		return x.Location
	***REMOVED***
	return nil
***REMOVED***

// A RouteNote is a message sent while at a given point.
type RouteNote struct ***REMOVED***
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The location from which the message is sent.
	Location *Point `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	// The message to be sent.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
***REMOVED***

func (x *RouteNote) Reset() ***REMOVED***
	*x = RouteNote***REMOVED******REMOVED***
	if protoimpl.UnsafeEnabled ***REMOVED***
		mi := &file_route_guide_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	***REMOVED***
***REMOVED***

func (x *RouteNote) String() string ***REMOVED***
	return protoimpl.X.MessageStringOf(x)
***REMOVED***

func (*RouteNote) ProtoMessage() ***REMOVED******REMOVED***

func (x *RouteNote) ProtoReflect() protoreflect.Message ***REMOVED***
	mi := &file_route_guide_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil ***REMOVED***
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil ***REMOVED***
			ms.StoreMessageInfo(mi)
		***REMOVED***
		return ms
	***REMOVED***
	return mi.MessageOf(x)
***REMOVED***

// Deprecated: Use RouteNote.ProtoReflect.Descriptor instead.
func (*RouteNote) Descriptor() ([]byte, []int) ***REMOVED***
	return file_route_guide_proto_rawDescGZIP(), []int***REMOVED***3***REMOVED***
***REMOVED***

func (x *RouteNote) GetLocation() *Point ***REMOVED***
	if x != nil ***REMOVED***
		return x.Location
	***REMOVED***
	return nil
***REMOVED***

func (x *RouteNote) GetMessage() string ***REMOVED***
	if x != nil ***REMOVED***
		return x.Message
	***REMOVED***
	return ""
***REMOVED***

// A RouteSummary is received in response to a RecordRoute rpc.
//
// It contains the number of individual points received, the number of
// detected features, and the total distance covered as the cumulative sum of
// the distance between each point.
type RouteSummary struct ***REMOVED***
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The number of points received.
	PointCount int32 `protobuf:"varint,1,opt,name=point_count,json=pointCount,proto3" json:"point_count,omitempty"`
	// The number of known features passed while traversing the route.
	FeatureCount int32 `protobuf:"varint,2,opt,name=feature_count,json=featureCount,proto3" json:"feature_count,omitempty"`
	// The distance covered in metres.
	Distance int32 `protobuf:"varint,3,opt,name=distance,proto3" json:"distance,omitempty"`
	// The duration of the traversal in seconds.
	ElapsedTime int32 `protobuf:"varint,4,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
***REMOVED***

func (x *RouteSummary) Reset() ***REMOVED***
	*x = RouteSummary***REMOVED******REMOVED***
	if protoimpl.UnsafeEnabled ***REMOVED***
		mi := &file_route_guide_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	***REMOVED***
***REMOVED***

func (x *RouteSummary) String() string ***REMOVED***
	return protoimpl.X.MessageStringOf(x)
***REMOVED***

func (*RouteSummary) ProtoMessage() ***REMOVED******REMOVED***

func (x *RouteSummary) ProtoReflect() protoreflect.Message ***REMOVED***
	mi := &file_route_guide_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil ***REMOVED***
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil ***REMOVED***
			ms.StoreMessageInfo(mi)
		***REMOVED***
		return ms
	***REMOVED***
	return mi.MessageOf(x)
***REMOVED***

// Deprecated: Use RouteSummary.ProtoReflect.Descriptor instead.
func (*RouteSummary) Descriptor() ([]byte, []int) ***REMOVED***
	return file_route_guide_proto_rawDescGZIP(), []int***REMOVED***4***REMOVED***
***REMOVED***

func (x *RouteSummary) GetPointCount() int32 ***REMOVED***
	if x != nil ***REMOVED***
		return x.PointCount
	***REMOVED***
	return 0
***REMOVED***

func (x *RouteSummary) GetFeatureCount() int32 ***REMOVED***
	if x != nil ***REMOVED***
		return x.FeatureCount
	***REMOVED***
	return 0
***REMOVED***

func (x *RouteSummary) GetDistance() int32 ***REMOVED***
	if x != nil ***REMOVED***
		return x.Distance
	***REMOVED***
	return 0
***REMOVED***

func (x *RouteSummary) GetElapsedTime() int32 ***REMOVED***
	if x != nil ***REMOVED***
		return x.ElapsedTime
	***REMOVED***
	return 0
***REMOVED***

var File_route_guide_proto protoreflect.FileDescriptor

var file_route_guide_proto_rawDesc = []byte***REMOVED***
	0x0a, 0x11, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x41, 0x0a, 0x05, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x45, 0x0a, 0x09,
	0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x02, 0x6c, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x02, 0x6c, 0x6f, 0x12, 0x1b, 0x0a, 0x02, 0x68, 0x69, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52,
	0x02, 0x68, 0x69, 0x22, 0x46, 0x0a, 0x07, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4e, 0x0a, 0x09, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x0c,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x32, 0xd5, 0x01, 0x0a, 0x0a, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x47, 0x75, 0x69, 0x64, 0x65,
	0x12, 0x2a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x0b,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x1a, 0x0d, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0c,
	0x4c, 0x69, 0x73, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x0f, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x1a, 0x0d, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x32, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12,
	0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x1a, 0x12, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x22, 0x00, 0x28, 0x01, 0x12, 0x33, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x43, 0x68, 0x61,
	0x74, 0x12, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4e, 0x6f,
	0x74, 0x65, 0x1a, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4e,
	0x6f, 0x74, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x6d,
	0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
***REMOVED***

var (
	file_route_guide_proto_rawDescOnce sync.Once
	file_route_guide_proto_rawDescData = file_route_guide_proto_rawDesc
)

func file_route_guide_proto_rawDescGZIP() []byte ***REMOVED***
	file_route_guide_proto_rawDescOnce.Do(func() ***REMOVED***
		file_route_guide_proto_rawDescData = protoimpl.X.CompressGZIP(file_route_guide_proto_rawDescData)
	***REMOVED***)
	return file_route_guide_proto_rawDescData
***REMOVED***

var file_route_guide_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_route_guide_proto_goTypes = []interface***REMOVED******REMOVED******REMOVED***
	(*Point)(nil),        // 0: main.Point
	(*Rectangle)(nil),    // 1: main.Rectangle
	(*Feature)(nil),      // 2: main.Feature
	(*RouteNote)(nil),    // 3: main.RouteNote
	(*RouteSummary)(nil), // 4: main.RouteSummary
***REMOVED***
var file_route_guide_proto_depIdxs = []int32***REMOVED***
	0, // 0: main.Rectangle.lo:type_name -> main.Point
	0, // 1: main.Rectangle.hi:type_name -> main.Point
	0, // 2: main.Feature.location:type_name -> main.Point
	0, // 3: main.RouteNote.location:type_name -> main.Point
	0, // 4: main.RouteGuide.GetFeature:input_type -> main.Point
	1, // 5: main.RouteGuide.ListFeatures:input_type -> main.Rectangle
	0, // 6: main.RouteGuide.RecordRoute:input_type -> main.Point
	3, // 7: main.RouteGuide.RouteChat:input_type -> main.RouteNote
	2, // 8: main.RouteGuide.GetFeature:output_type -> main.Feature
	2, // 9: main.RouteGuide.ListFeatures:output_type -> main.Feature
	4, // 10: main.RouteGuide.RecordRoute:output_type -> main.RouteSummary
	3, // 11: main.RouteGuide.RouteChat:output_type -> main.RouteNote
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
***REMOVED***

func init() ***REMOVED*** file_route_guide_proto_init() ***REMOVED***
func file_route_guide_proto_init() ***REMOVED***
	if File_route_guide_proto != nil ***REMOVED***
		return
	***REMOVED***
	if !protoimpl.UnsafeEnabled ***REMOVED***
		file_route_guide_proto_msgTypes[0].Exporter = func(v interface***REMOVED******REMOVED***, i int) interface***REMOVED******REMOVED*** ***REMOVED***
			switch v := v.(*Point); i ***REMOVED***
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			***REMOVED***
		***REMOVED***
		file_route_guide_proto_msgTypes[1].Exporter = func(v interface***REMOVED******REMOVED***, i int) interface***REMOVED******REMOVED*** ***REMOVED***
			switch v := v.(*Rectangle); i ***REMOVED***
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			***REMOVED***
		***REMOVED***
		file_route_guide_proto_msgTypes[2].Exporter = func(v interface***REMOVED******REMOVED***, i int) interface***REMOVED******REMOVED*** ***REMOVED***
			switch v := v.(*Feature); i ***REMOVED***
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			***REMOVED***
		***REMOVED***
		file_route_guide_proto_msgTypes[3].Exporter = func(v interface***REMOVED******REMOVED***, i int) interface***REMOVED******REMOVED*** ***REMOVED***
			switch v := v.(*RouteNote); i ***REMOVED***
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			***REMOVED***
		***REMOVED***
		file_route_guide_proto_msgTypes[4].Exporter = func(v interface***REMOVED******REMOVED***, i int) interface***REMOVED******REMOVED*** ***REMOVED***
			switch v := v.(*RouteSummary); i ***REMOVED***
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			***REMOVED***
		***REMOVED***
	***REMOVED***
	type x struct***REMOVED******REMOVED***
	out := protoimpl.TypeBuilder***REMOVED***
		File: protoimpl.DescBuilder***REMOVED***
			GoPackagePath: reflect.TypeOf(x***REMOVED******REMOVED***).PkgPath(),
			RawDescriptor: file_route_guide_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		***REMOVED***,
		GoTypes:           file_route_guide_proto_goTypes,
		DependencyIndexes: file_route_guide_proto_depIdxs,
		MessageInfos:      file_route_guide_proto_msgTypes,
	***REMOVED***.Build()
	File_route_guide_proto = out.File
	file_route_guide_proto_rawDesc = nil
	file_route_guide_proto_goTypes = nil
	file_route_guide_proto_depIdxs = nil
***REMOVED***

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RouteGuideClient is the client API for RouteGuide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouteGuideClient interface ***REMOVED***
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (RouteGuide_ListFeaturesClient, error)
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	RecordRoute(ctx context.Context, opts ...grpc.CallOption) (RouteGuide_RecordRouteClient, error)
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	RouteChat(ctx context.Context, opts ...grpc.CallOption) (RouteGuide_RouteChatClient, error)
***REMOVED***

type routeGuideClient struct ***REMOVED***
	cc grpc.ClientConnInterface
***REMOVED***

func NewRouteGuideClient(cc grpc.ClientConnInterface) RouteGuideClient ***REMOVED***
	return &routeGuideClient***REMOVED***cc***REMOVED***
***REMOVED***

func (c *routeGuideClient) GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error) ***REMOVED***
	out := new(Feature)
	err := c.cc.Invoke(ctx, "/main.RouteGuide/GetFeature", in, out, opts...)
	if err != nil ***REMOVED***
		return nil, err
	***REMOVED***
	return out, nil
***REMOVED***

func (c *routeGuideClient) ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (RouteGuide_ListFeaturesClient, error) ***REMOVED***
	stream, err := c.cc.NewStream(ctx, &_RouteGuide_serviceDesc.Streams[0], "/main.RouteGuide/ListFeatures", opts...)
	if err != nil ***REMOVED***
		return nil, err
	***REMOVED***
	x := &routeGuideListFeaturesClient***REMOVED***stream***REMOVED***
	if err := x.ClientStream.SendMsg(in); err != nil ***REMOVED***
		return nil, err
	***REMOVED***
	if err := x.ClientStream.CloseSend(); err != nil ***REMOVED***
		return nil, err
	***REMOVED***
	return x, nil
***REMOVED***

type RouteGuide_ListFeaturesClient interface ***REMOVED***
	Recv() (*Feature, error)
	grpc.ClientStream
***REMOVED***

type routeGuideListFeaturesClient struct ***REMOVED***
	grpc.ClientStream
***REMOVED***

func (x *routeGuideListFeaturesClient) Recv() (*Feature, error) ***REMOVED***
	m := new(Feature)
	if err := x.ClientStream.RecvMsg(m); err != nil ***REMOVED***
		return nil, err
	***REMOVED***
	return m, nil
***REMOVED***

func (c *routeGuideClient) RecordRoute(ctx context.Context, opts ...grpc.CallOption) (RouteGuide_RecordRouteClient, error) ***REMOVED***
	stream, err := c.cc.NewStream(ctx, &_RouteGuide_serviceDesc.Streams[1], "/main.RouteGuide/RecordRoute", opts...)
	if err != nil ***REMOVED***
		return nil, err
	***REMOVED***
	x := &routeGuideRecordRouteClient***REMOVED***stream***REMOVED***
	return x, nil
***REMOVED***

type RouteGuide_RecordRouteClient interface ***REMOVED***
	Send(*Point) error
	CloseAndRecv() (*RouteSummary, error)
	grpc.ClientStream
***REMOVED***

type routeGuideRecordRouteClient struct ***REMOVED***
	grpc.ClientStream
***REMOVED***

func (x *routeGuideRecordRouteClient) Send(m *Point) error ***REMOVED***
	return x.ClientStream.SendMsg(m)
***REMOVED***

func (x *routeGuideRecordRouteClient) CloseAndRecv() (*RouteSummary, error) ***REMOVED***
	if err := x.ClientStream.CloseSend(); err != nil ***REMOVED***
		return nil, err
	***REMOVED***
	m := new(RouteSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil ***REMOVED***
		return nil, err
	***REMOVED***
	return m, nil
***REMOVED***

func (c *routeGuideClient) RouteChat(ctx context.Context, opts ...grpc.CallOption) (RouteGuide_RouteChatClient, error) ***REMOVED***
	stream, err := c.cc.NewStream(ctx, &_RouteGuide_serviceDesc.Streams[2], "/main.RouteGuide/RouteChat", opts...)
	if err != nil ***REMOVED***
		return nil, err
	***REMOVED***
	x := &routeGuideRouteChatClient***REMOVED***stream***REMOVED***
	return x, nil
***REMOVED***

type RouteGuide_RouteChatClient interface ***REMOVED***
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc.ClientStream
***REMOVED***

type routeGuideRouteChatClient struct ***REMOVED***
	grpc.ClientStream
***REMOVED***

func (x *routeGuideRouteChatClient) Send(m *RouteNote) error ***REMOVED***
	return x.ClientStream.SendMsg(m)
***REMOVED***

func (x *routeGuideRouteChatClient) Recv() (*RouteNote, error) ***REMOVED***
	m := new(RouteNote)
	if err := x.ClientStream.RecvMsg(m); err != nil ***REMOVED***
		return nil, err
	***REMOVED***
	return m, nil
***REMOVED***

// RouteGuideServer is the server API for RouteGuide service.
type RouteGuideServer interface ***REMOVED***
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(context.Context, *Point) (*Feature, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	ListFeatures(*Rectangle, RouteGuide_ListFeaturesServer) error
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	RecordRoute(RouteGuide_RecordRouteServer) error
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	RouteChat(RouteGuide_RouteChatServer) error
***REMOVED***

// UnimplementedRouteGuideServer can be embedded to have forward compatible implementations.
type UnimplementedRouteGuideServer struct ***REMOVED***
***REMOVED***

func (*UnimplementedRouteGuideServer) GetFeature(context.Context, *Point) (*Feature, error) ***REMOVED***
	return nil, status.Errorf(codes.Unimplemented, "method GetFeature not implemented")
***REMOVED***
func (*UnimplementedRouteGuideServer) ListFeatures(*Rectangle, RouteGuide_ListFeaturesServer) error ***REMOVED***
	return status.Errorf(codes.Unimplemented, "method ListFeatures not implemented")
***REMOVED***
func (*UnimplementedRouteGuideServer) RecordRoute(RouteGuide_RecordRouteServer) error ***REMOVED***
	return status.Errorf(codes.Unimplemented, "method RecordRoute not implemented")
***REMOVED***
func (*UnimplementedRouteGuideServer) RouteChat(RouteGuide_RouteChatServer) error ***REMOVED***
	return status.Errorf(codes.Unimplemented, "method RouteChat not implemented")
***REMOVED***

func RegisterRouteGuideServer(s *grpc.Server, srv RouteGuideServer) ***REMOVED***
	s.RegisterService(&_RouteGuide_serviceDesc, srv)
***REMOVED***

func _RouteGuide_GetFeature_Handler(srv interface***REMOVED******REMOVED***, ctx context.Context, dec func(interface***REMOVED******REMOVED***) error, interceptor grpc.UnaryServerInterceptor) (interface***REMOVED******REMOVED***, error) ***REMOVED***
	in := new(Point)
	if err := dec(in); err != nil ***REMOVED***
		return nil, err
	***REMOVED***
	if interceptor == nil ***REMOVED***
		return srv.(RouteGuideServer).GetFeature(ctx, in)
	***REMOVED***
	info := &grpc.UnaryServerInfo***REMOVED***
		Server:     srv,
		FullMethod: "/main.RouteGuide/GetFeature",
	***REMOVED***
	handler := func(ctx context.Context, req interface***REMOVED******REMOVED***) (interface***REMOVED******REMOVED***, error) ***REMOVED***
		return srv.(RouteGuideServer).GetFeature(ctx, req.(*Point))
	***REMOVED***
	return interceptor(ctx, in, info, handler)
***REMOVED***

func _RouteGuide_ListFeatures_Handler(srv interface***REMOVED******REMOVED***, stream grpc.ServerStream) error ***REMOVED***
	m := new(Rectangle)
	if err := stream.RecvMsg(m); err != nil ***REMOVED***
		return err
	***REMOVED***
	return srv.(RouteGuideServer).ListFeatures(m, &routeGuideListFeaturesServer***REMOVED***stream***REMOVED***)
***REMOVED***

type RouteGuide_ListFeaturesServer interface ***REMOVED***
	Send(*Feature) error
	grpc.ServerStream
***REMOVED***

type routeGuideListFeaturesServer struct ***REMOVED***
	grpc.ServerStream
***REMOVED***

func (x *routeGuideListFeaturesServer) Send(m *Feature) error ***REMOVED***
	return x.ServerStream.SendMsg(m)
***REMOVED***

func _RouteGuide_RecordRoute_Handler(srv interface***REMOVED******REMOVED***, stream grpc.ServerStream) error ***REMOVED***
	return srv.(RouteGuideServer).RecordRoute(&routeGuideRecordRouteServer***REMOVED***stream***REMOVED***)
***REMOVED***

type RouteGuide_RecordRouteServer interface ***REMOVED***
	SendAndClose(*RouteSummary) error
	Recv() (*Point, error)
	grpc.ServerStream
***REMOVED***

type routeGuideRecordRouteServer struct ***REMOVED***
	grpc.ServerStream
***REMOVED***

func (x *routeGuideRecordRouteServer) SendAndClose(m *RouteSummary) error ***REMOVED***
	return x.ServerStream.SendMsg(m)
***REMOVED***

func (x *routeGuideRecordRouteServer) Recv() (*Point, error) ***REMOVED***
	m := new(Point)
	if err := x.ServerStream.RecvMsg(m); err != nil ***REMOVED***
		return nil, err
	***REMOVED***
	return m, nil
***REMOVED***

func _RouteGuide_RouteChat_Handler(srv interface***REMOVED******REMOVED***, stream grpc.ServerStream) error ***REMOVED***
	return srv.(RouteGuideServer).RouteChat(&routeGuideRouteChatServer***REMOVED***stream***REMOVED***)
***REMOVED***

type RouteGuide_RouteChatServer interface ***REMOVED***
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc.ServerStream
***REMOVED***

type routeGuideRouteChatServer struct ***REMOVED***
	grpc.ServerStream
***REMOVED***

func (x *routeGuideRouteChatServer) Send(m *RouteNote) error ***REMOVED***
	return x.ServerStream.SendMsg(m)
***REMOVED***

func (x *routeGuideRouteChatServer) Recv() (*RouteNote, error) ***REMOVED***
	m := new(RouteNote)
	if err := x.ServerStream.RecvMsg(m); err != nil ***REMOVED***
		return nil, err
	***REMOVED***
	return m, nil
***REMOVED***

var _RouteGuide_serviceDesc = grpc.ServiceDesc***REMOVED***
	ServiceName: "main.RouteGuide",
	HandlerType: (*RouteGuideServer)(nil),
	Methods: []grpc.MethodDesc***REMOVED***
		***REMOVED***
			MethodName: "GetFeature",
			Handler:    _RouteGuide_GetFeature_Handler,
		***REMOVED***,
	***REMOVED***,
	Streams: []grpc.StreamDesc***REMOVED***
		***REMOVED***
			StreamName:    "ListFeatures",
			Handler:       _RouteGuide_ListFeatures_Handler,
			ServerStreams: true,
		***REMOVED***,
		***REMOVED***
			StreamName:    "RecordRoute",
			Handler:       _RouteGuide_RecordRoute_Handler,
			ClientStreams: true,
		***REMOVED***,
		***REMOVED***
			StreamName:    "RouteChat",
			Handler:       _RouteGuide_RouteChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		***REMOVED***,
	***REMOVED***,
	Metadata: "route_guide.proto",
***REMOVED***
