// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: route_guide.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Points are represented as latitude-longitude pairs in the E7 representation
// (degrees multiplied by 10**7 and rounded to the nearest integer).
// Latitudes should be in the range +/- 90 degrees and longitude should be in
// the range +/- 180 degrees (inclusive).
type Point struct ***REMOVED***
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  int32 `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude int32 `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
***REMOVED***

func (x *Point) Reset() ***REMOVED***
	*x = Point***REMOVED******REMOVED***
	if protoimpl.UnsafeEnabled ***REMOVED***
		mi := &file_route_guide_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	***REMOVED***
***REMOVED***

func (x *Point) String() string ***REMOVED***
	return protoimpl.X.MessageStringOf(x)
***REMOVED***

func (*Point) ProtoMessage() ***REMOVED******REMOVED***

func (x *Point) ProtoReflect() protoreflect.Message ***REMOVED***
	mi := &file_route_guide_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil ***REMOVED***
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil ***REMOVED***
			ms.StoreMessageInfo(mi)
		***REMOVED***
		return ms
	***REMOVED***
	return mi.MessageOf(x)
***REMOVED***

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) ***REMOVED***
	return file_route_guide_proto_rawDescGZIP(), []int***REMOVED***0***REMOVED***
***REMOVED***

func (x *Point) GetLatitude() int32 ***REMOVED***
	if x != nil ***REMOVED***
		return x.Latitude
	***REMOVED***
	return 0
***REMOVED***

func (x *Point) GetLongitude() int32 ***REMOVED***
	if x != nil ***REMOVED***
		return x.Longitude
	***REMOVED***
	return 0
***REMOVED***

// A latitude-longitude rectangle, represented as two diagonally opposite
// points "lo" and "hi".
type Rectangle struct ***REMOVED***
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// One corner of the rectangle.
	Lo *Point `protobuf:"bytes,1,opt,name=lo,proto3" json:"lo,omitempty"`
	// The other corner of the rectangle.
	Hi *Point `protobuf:"bytes,2,opt,name=hi,proto3" json:"hi,omitempty"`
***REMOVED***

func (x *Rectangle) Reset() ***REMOVED***
	*x = Rectangle***REMOVED******REMOVED***
	if protoimpl.UnsafeEnabled ***REMOVED***
		mi := &file_route_guide_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	***REMOVED***
***REMOVED***

func (x *Rectangle) String() string ***REMOVED***
	return protoimpl.X.MessageStringOf(x)
***REMOVED***

func (*Rectangle) ProtoMessage() ***REMOVED******REMOVED***

func (x *Rectangle) ProtoReflect() protoreflect.Message ***REMOVED***
	mi := &file_route_guide_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil ***REMOVED***
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil ***REMOVED***
			ms.StoreMessageInfo(mi)
		***REMOVED***
		return ms
	***REMOVED***
	return mi.MessageOf(x)
***REMOVED***

// Deprecated: Use Rectangle.ProtoReflect.Descriptor instead.
func (*Rectangle) Descriptor() ([]byte, []int) ***REMOVED***
	return file_route_guide_proto_rawDescGZIP(), []int***REMOVED***1***REMOVED***
***REMOVED***

func (x *Rectangle) GetLo() *Point ***REMOVED***
	if x != nil ***REMOVED***
		return x.Lo
	***REMOVED***
	return nil
***REMOVED***

func (x *Rectangle) GetHi() *Point ***REMOVED***
	if x != nil ***REMOVED***
		return x.Hi
	***REMOVED***
	return nil
***REMOVED***

// A feature names something at a given point.
//
// If a feature could not be named, the name is empty.
type Feature struct ***REMOVED***
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the feature.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The point where the feature is detected.
	Location *Point `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
***REMOVED***

func (x *Feature) Reset() ***REMOVED***
	*x = Feature***REMOVED******REMOVED***
	if protoimpl.UnsafeEnabled ***REMOVED***
		mi := &file_route_guide_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	***REMOVED***
***REMOVED***

func (x *Feature) String() string ***REMOVED***
	return protoimpl.X.MessageStringOf(x)
***REMOVED***

func (*Feature) ProtoMessage() ***REMOVED******REMOVED***

func (x *Feature) ProtoReflect() protoreflect.Message ***REMOVED***
	mi := &file_route_guide_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil ***REMOVED***
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil ***REMOVED***
			ms.StoreMessageInfo(mi)
		***REMOVED***
		return ms
	***REMOVED***
	return mi.MessageOf(x)
***REMOVED***

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) ***REMOVED***
	return file_route_guide_proto_rawDescGZIP(), []int***REMOVED***2***REMOVED***
***REMOVED***

func (x *Feature) GetName() string ***REMOVED***
	if x != nil ***REMOVED***
		return x.Name
	***REMOVED***
	return ""
***REMOVED***

func (x *Feature) GetLocation() *Point ***REMOVED***
	if x != nil ***REMOVED***
		return x.Location
	***REMOVED***
	return nil
***REMOVED***

// A RouteNote is a message sent while at a given point.
type RouteNote struct ***REMOVED***
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The location from which the message is sent.
	Location *Point `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	// The message to be sent.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
***REMOVED***

func (x *RouteNote) Reset() ***REMOVED***
	*x = RouteNote***REMOVED******REMOVED***
	if protoimpl.UnsafeEnabled ***REMOVED***
		mi := &file_route_guide_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	***REMOVED***
***REMOVED***

func (x *RouteNote) String() string ***REMOVED***
	return protoimpl.X.MessageStringOf(x)
***REMOVED***

func (*RouteNote) ProtoMessage() ***REMOVED******REMOVED***

func (x *RouteNote) ProtoReflect() protoreflect.Message ***REMOVED***
	mi := &file_route_guide_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil ***REMOVED***
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil ***REMOVED***
			ms.StoreMessageInfo(mi)
		***REMOVED***
		return ms
	***REMOVED***
	return mi.MessageOf(x)
***REMOVED***

// Deprecated: Use RouteNote.ProtoReflect.Descriptor instead.
func (*RouteNote) Descriptor() ([]byte, []int) ***REMOVED***
	return file_route_guide_proto_rawDescGZIP(), []int***REMOVED***3***REMOVED***
***REMOVED***

func (x *RouteNote) GetLocation() *Point ***REMOVED***
	if x != nil ***REMOVED***
		return x.Location
	***REMOVED***
	return nil
***REMOVED***

func (x *RouteNote) GetMessage() string ***REMOVED***
	if x != nil ***REMOVED***
		return x.Message
	***REMOVED***
	return ""
***REMOVED***

// A RouteSummary is received in response to a RecordRoute rpc.
//
// It contains the number of individual points received, the number of
// detected features, and the total distance covered as the cumulative sum of
// the distance between each point.
type RouteSummary struct ***REMOVED***
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The number of points received.
	PointCount int32 `protobuf:"varint,1,opt,name=point_count,json=pointCount,proto3" json:"point_count,omitempty"`
	// The number of known features passed while traversing the route.
	FeatureCount int32 `protobuf:"varint,2,opt,name=feature_count,json=featureCount,proto3" json:"feature_count,omitempty"`
	// The distance covered in metres.
	Distance int32 `protobuf:"varint,3,opt,name=distance,proto3" json:"distance,omitempty"`
	// The duration of the traversal in seconds.
	ElapsedTime int32 `protobuf:"varint,4,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
***REMOVED***

func (x *RouteSummary) Reset() ***REMOVED***
	*x = RouteSummary***REMOVED******REMOVED***
	if protoimpl.UnsafeEnabled ***REMOVED***
		mi := &file_route_guide_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	***REMOVED***
***REMOVED***

func (x *RouteSummary) String() string ***REMOVED***
	return protoimpl.X.MessageStringOf(x)
***REMOVED***

func (*RouteSummary) ProtoMessage() ***REMOVED******REMOVED***

func (x *RouteSummary) ProtoReflect() protoreflect.Message ***REMOVED***
	mi := &file_route_guide_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil ***REMOVED***
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil ***REMOVED***
			ms.StoreMessageInfo(mi)
		***REMOVED***
		return ms
	***REMOVED***
	return mi.MessageOf(x)
***REMOVED***

// Deprecated: Use RouteSummary.ProtoReflect.Descriptor instead.
func (*RouteSummary) Descriptor() ([]byte, []int) ***REMOVED***
	return file_route_guide_proto_rawDescGZIP(), []int***REMOVED***4***REMOVED***
***REMOVED***

func (x *RouteSummary) GetPointCount() int32 ***REMOVED***
	if x != nil ***REMOVED***
		return x.PointCount
	***REMOVED***
	return 0
***REMOVED***

func (x *RouteSummary) GetFeatureCount() int32 ***REMOVED***
	if x != nil ***REMOVED***
		return x.FeatureCount
	***REMOVED***
	return 0
***REMOVED***

func (x *RouteSummary) GetDistance() int32 ***REMOVED***
	if x != nil ***REMOVED***
		return x.Distance
	***REMOVED***
	return 0
***REMOVED***

func (x *RouteSummary) GetElapsedTime() int32 ***REMOVED***
	if x != nil ***REMOVED***
		return x.ElapsedTime
	***REMOVED***
	return 0
***REMOVED***

var File_route_guide_proto protoreflect.FileDescriptor

var file_route_guide_proto_rawDesc = []byte***REMOVED***
	0x0a, 0x11, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x41, 0x0a, 0x05, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x45, 0x0a, 0x09,
	0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x02, 0x6c, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x02, 0x6c, 0x6f, 0x12, 0x1b, 0x0a, 0x02, 0x68, 0x69, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52,
	0x02, 0x68, 0x69, 0x22, 0x46, 0x0a, 0x07, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4e, 0x0a, 0x09, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x0c,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x32, 0x71, 0x0a, 0x0f, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x45, 0x78, 0x70, 0x6c,
	0x6f, 0x72, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x1a,
	0x0d, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x00,
	0x12, 0x32, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x12, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c,
	0x65, 0x1a, 0x0d, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x32, 0x75, 0x0a, 0x0a, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x47, 0x75, 0x69,
	0x64, 0x65, 0x12, 0x32, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x12, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x1a, 0x12,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x22, 0x00, 0x28, 0x01, 0x12, 0x33, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x43,
	0x68, 0x61, 0x74, 0x12, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x4e, 0x6f, 0x74, 0x65, 0x1a, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x4e, 0x6f, 0x74, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x3b, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
***REMOVED***

var (
	file_route_guide_proto_rawDescOnce sync.Once
	file_route_guide_proto_rawDescData = file_route_guide_proto_rawDesc
)

func file_route_guide_proto_rawDescGZIP() []byte ***REMOVED***
	file_route_guide_proto_rawDescOnce.Do(func() ***REMOVED***
		file_route_guide_proto_rawDescData = protoimpl.X.CompressGZIP(file_route_guide_proto_rawDescData)
	***REMOVED***)
	return file_route_guide_proto_rawDescData
***REMOVED***

var file_route_guide_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_route_guide_proto_goTypes = []interface***REMOVED******REMOVED******REMOVED***
	(*Point)(nil),        // 0: main.Point
	(*Rectangle)(nil),    // 1: main.Rectangle
	(*Feature)(nil),      // 2: main.Feature
	(*RouteNote)(nil),    // 3: main.RouteNote
	(*RouteSummary)(nil), // 4: main.RouteSummary
***REMOVED***
var file_route_guide_proto_depIdxs = []int32***REMOVED***
	0, // 0: main.Rectangle.lo:type_name -> main.Point
	0, // 1: main.Rectangle.hi:type_name -> main.Point
	0, // 2: main.Feature.location:type_name -> main.Point
	0, // 3: main.RouteNote.location:type_name -> main.Point
	0, // 4: main.FeatureExplorer.GetFeature:input_type -> main.Point
	1, // 5: main.FeatureExplorer.ListFeatures:input_type -> main.Rectangle
	0, // 6: main.RouteGuide.RecordRoute:input_type -> main.Point
	3, // 7: main.RouteGuide.RouteChat:input_type -> main.RouteNote
	2, // 8: main.FeatureExplorer.GetFeature:output_type -> main.Feature
	2, // 9: main.FeatureExplorer.ListFeatures:output_type -> main.Feature
	4, // 10: main.RouteGuide.RecordRoute:output_type -> main.RouteSummary
	3, // 11: main.RouteGuide.RouteChat:output_type -> main.RouteNote
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
***REMOVED***

func init() ***REMOVED*** file_route_guide_proto_init() ***REMOVED***
func file_route_guide_proto_init() ***REMOVED***
	if File_route_guide_proto != nil ***REMOVED***
		return
	***REMOVED***
	if !protoimpl.UnsafeEnabled ***REMOVED***
		file_route_guide_proto_msgTypes[0].Exporter = func(v interface***REMOVED******REMOVED***, i int) interface***REMOVED******REMOVED*** ***REMOVED***
			switch v := v.(*Point); i ***REMOVED***
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			***REMOVED***
		***REMOVED***
		file_route_guide_proto_msgTypes[1].Exporter = func(v interface***REMOVED******REMOVED***, i int) interface***REMOVED******REMOVED*** ***REMOVED***
			switch v := v.(*Rectangle); i ***REMOVED***
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			***REMOVED***
		***REMOVED***
		file_route_guide_proto_msgTypes[2].Exporter = func(v interface***REMOVED******REMOVED***, i int) interface***REMOVED******REMOVED*** ***REMOVED***
			switch v := v.(*Feature); i ***REMOVED***
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			***REMOVED***
		***REMOVED***
		file_route_guide_proto_msgTypes[3].Exporter = func(v interface***REMOVED******REMOVED***, i int) interface***REMOVED******REMOVED*** ***REMOVED***
			switch v := v.(*RouteNote); i ***REMOVED***
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			***REMOVED***
		***REMOVED***
		file_route_guide_proto_msgTypes[4].Exporter = func(v interface***REMOVED******REMOVED***, i int) interface***REMOVED******REMOVED*** ***REMOVED***
			switch v := v.(*RouteSummary); i ***REMOVED***
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			***REMOVED***
		***REMOVED***
	***REMOVED***
	type x struct***REMOVED******REMOVED***
	out := protoimpl.TypeBuilder***REMOVED***
		File: protoimpl.DescBuilder***REMOVED***
			GoPackagePath: reflect.TypeOf(x***REMOVED******REMOVED***).PkgPath(),
			RawDescriptor: file_route_guide_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		***REMOVED***,
		GoTypes:           file_route_guide_proto_goTypes,
		DependencyIndexes: file_route_guide_proto_depIdxs,
		MessageInfos:      file_route_guide_proto_msgTypes,
	***REMOVED***.Build()
	File_route_guide_proto = out.File
	file_route_guide_proto_rawDesc = nil
	file_route_guide_proto_goTypes = nil
	file_route_guide_proto_depIdxs = nil
***REMOVED***
