// Code generated by "enumer -type=TimeFormat -transform=snake -trimprefix TimeFormat -output time_format_gen.go"; DO NOT EDIT.

//
package csv

import (
	"fmt"
)

const _TimeFormatName = "unixrfc3339"

var _TimeFormatIndex = [...]uint8***REMOVED***0, 4, 11***REMOVED***

func (i TimeFormat) String() string ***REMOVED***
	if i >= TimeFormat(len(_TimeFormatIndex)-1) ***REMOVED***
		return fmt.Sprintf("TimeFormat(%d)", i)
	***REMOVED***
	return _TimeFormatName[_TimeFormatIndex[i]:_TimeFormatIndex[i+1]]
***REMOVED***

var _TimeFormatValues = []TimeFormat***REMOVED***0, 1***REMOVED***

var _TimeFormatNameToValueMap = map[string]TimeFormat***REMOVED***
	_TimeFormatName[0:4]:  0,
	_TimeFormatName[4:11]: 1,
***REMOVED***

// TimeFormatString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TimeFormatString(s string) (TimeFormat, error) ***REMOVED***
	if val, ok := _TimeFormatNameToValueMap[s]; ok ***REMOVED***
		return val, nil
	***REMOVED***
	return 0, fmt.Errorf("%s does not belong to TimeFormat values", s)
***REMOVED***

// TimeFormatValues returns all values of the enum
func TimeFormatValues() []TimeFormat ***REMOVED***
	return _TimeFormatValues
***REMOVED***

// IsATimeFormat returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TimeFormat) IsATimeFormat() bool ***REMOVED***
	for _, v := range _TimeFormatValues ***REMOVED***
		if i == v ***REMOVED***
			return true
		***REMOVED***
	***REMOVED***
	return false
***REMOVED***
