export ORCHESTRATOR_REDIS_PASSWORD=
export ORCHESTRATOR_REDIS_HOST=
export ORCHESTRATOR_REDIS_PORT=
export WORKER_0_PASSWORD=
export WORKER_0_HOST=
export WORKER_0_PORT=
export WORKER_0_DISPLAY_NAME=

export STORE_MONGO_USER=
export STORE_MONGO_PASSWORD=
export STORE_MONGO_HOST=
export STORE_MONGO_PORT=
export STORE_MONGO_DATABASE=

export IS_MASTER=true

go run main.go --mode=orchestrator