name: CI
on:
  # Enable manually triggering this workflow via the API or web UI
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

defaults:
  run:
    shell: bash

env:
  APP_NAME: "k6"
  # We'll push to two DockerHub repos at once; `loadimpact/k6` repo is required for backwards compatibility
  LI_DOCKER_IMAGE_ID: "loadimpact/k6"
  DOCKER_IMAGE_ID: "grafana/k6"
  GHCR_IMAGE_ID: $***REMOVED******REMOVED*** github.repository ***REMOVED******REMOVED***

jobs:
  test-prev:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest, windows-2019]
    runs-on: $***REMOVED******REMOVED*** matrix.platform ***REMOVED******REMOVED***
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: $***REMOVED******REMOVED*** matrix.go-version ***REMOVED******REMOVED***
      - name: Run tests
        run: |
          set -x
          go version
          export GOMAXPROCS=2
          args=("-p" "2" "-race")
          # Run with less concurrency on Windows to minimize flakiness.
          if [[ "$***REMOVED******REMOVED*** matrix.platform ***REMOVED******REMOVED***" == windows* ]]; then
            unset args[2]
            args[1]="1"
            export GOMAXPROCS=1
          fi
          go test "$***REMOVED***args[@]***REMOVED***" -timeout 800s ./...

  test-tip:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: Install Go tip
        run: |
          go install golang.org/dl/gotip@latest
          gotip download
          echo "GOROOT=$HOME/sdk/gotip" >> "$GITHUB_ENV"
          echo "GOPATH=$HOME/go" >> "$GITHUB_ENV"
          echo "$HOME/go/bin" >> "$GITHUB_PATH"
          echo "$HOME/sdk/gotip/bin" >> "$GITHUB_PATH"
      - name: Run tests
        run: |
          set -x
          which go
          go version
          export GOMAXPROCS=2
          args=("-p" "2" "-race")
          go test "$***REMOVED***args[@]***REMOVED***" -timeout 800s ./...

  test-current-cov:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest, windows-2019]
    runs-on: $***REMOVED******REMOVED*** matrix.platform ***REMOVED******REMOVED***
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: $***REMOVED******REMOVED*** matrix.go-version ***REMOVED******REMOVED***
      - name: Run tests with code coverage
        run: |
          go version
          export GOMAXPROCS=2
          args=("-p" "2" "-race")
          # Run with less concurrency on Windows to minimize flakiness.
          if [[ "$***REMOVED******REMOVED*** matrix.platform ***REMOVED******REMOVED***" == windows* ]]; then
            unset args[2]
            args[1]="1"
            export GOMAXPROCS=1
          fi
          echo "mode: set" > coverage.txt
          for pkg in $(go list ./... | grep -v vendor); do
              list=$(go list -test -f  '***REMOVED******REMOVED*** join .Deps  "\n"***REMOVED******REMOVED***' $pkg | grep go.k6.io/k6 | grep -v vendor || true)
              if [ -n "$list" ]; then
                  list=$(echo "$list" | cut -f1 -d ' ' | sort -u | paste -sd, -)
              fi

              go test "$***REMOVED***args[@]***REMOVED***" -timeout 800s --coverpkg="$list" -coverprofile=$(echo $pkg | tr / -).coverage $pkg
          done
          grep -h -v "^mode:" *.coverage >> coverage.txt
          rm -f *.coverage
      - name: Upload coverage to Codecov
        env:
          CODECOV_BASH_VERSION: 1.0.1
          CODECOV_BASH_SHA512SUM: d075b412a362a9a2b7aedfec3b8b9a9a927b3b99e98c7c15a2b76ef09862aeb005e91d76a5fd71b511141496d0fd23d1b42095f722ebcd509d768fba030f159e
          CODECOV_TOKEN: $***REMOVED******REMOVED*** secrets.CODECOV_TOKEN ***REMOVED******REMOVED***
        run: |
          curl -fsSLO "https://raw.githubusercontent.com/codecov/codecov-bash/$***REMOVED***CODECOV_BASH_VERSION***REMOVED***/codecov"
          echo "$CODECOV_BASH_SHA512SUM codecov" | sha512sum -c -
          platform="$***REMOVED******REMOVED*** matrix.platform ***REMOVED******REMOVED***"
          bash ./codecov -F "$***REMOVED***platform%%-****REMOVED***"
      - name: Generate coverage HTML report
        run: go tool cover -html=coverage.txt -o coverage.html
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-report-$***REMOVED******REMOVED*** matrix.platform ***REMOVED******REMOVED***
          path: coverage.html

  configure:
    runs-on: ubuntu-latest
    outputs:
      version: $***REMOVED******REMOVED*** steps.get_version.outputs.version ***REMOVED******REMOVED***
    steps:
      - name: Checkout code
        if: $***REMOVED******REMOVED*** ! startsWith(github.ref, 'refs/tags/v') ***REMOVED******REMOVED***
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get version
        id: get_version
        run: |
          set -x
          if [[ "$GITHUB_REF" =~ ^refs/tags/v.+$ ]]; then
            VERSION="$***REMOVED***GITHUB_REF##*/***REMOVED***"
            echo "Building real version tag '$GITHUB_REF', parsed '$VERSION' as the actual version..."
          else
            VERSION="$(git describe --tags --always --long --dirty)"
            echo "Building a non-version ref '$GITHUB_REF', use '$VERSION' as the version instead..."
          fi
          echo "VERSION=$***REMOVED***VERSION***REMOVED***"
          echo "::set-output name=version::$***REMOVED***VERSION***REMOVED***"

  build:
    runs-on: ubuntu-latest
    needs: [configure]
    env:
      VERSION: $***REMOVED******REMOVED*** needs.configure.outputs.version ***REMOVED******REMOVED***
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Install nfpm (dep and rpm package builder)
        run: |
          go install github.com/goreleaser/nfpm/v2/cmd/nfpm@v2.16.0
      - name: Install goversioninfo (.syso file creator)
        run: |
          go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@v1.4.0
      - name: Generate Windows binary metadata (.syso files)
        run: |
          IFS=. read -a version_parts <<< "$***REMOVED***VERSION#v***REMOVED***"
          IFS=- read -a version_patch <<< "$***REMOVED***version_parts[2]***REMOVED***"

          # Need a blank versioninfo.json for the CLI overrides to work.
          echo '***REMOVED******REMOVED***' > versioninfo.json
          set -x
          goversioninfo -64 \
            -platform-specific=true \
            -charset="1200" \
            -company="Raintank Inc. d.b.a. Grafana Labs" \
            -copyright="© Raintank Inc. d.b.a. Grafana Labs. Licensed under AGPL." \
            -description="A modern load testing tool, using Go and JavaScript" \
            -icon=packaging/k6.ico \
            -internal-name="k6" \
            -original-name="k6.exe" \
            -product-name="k6" \
            -translation="0x0409" \
            -ver-major="$***REMOVED***version_parts[0]***REMOVED***" \
            -ver-minor="$***REMOVED***version_parts[1]***REMOVED***" \
            -ver-patch="$***REMOVED***version_patch[0]***REMOVED***" \
            -special-build=$(IFS='-'; echo "$***REMOVED***version_patch[*]:1***REMOVED***";) \
            -product-version="$***REMOVED***VERSION#v***REMOVED***"

          set +x
          ls -lah | grep -i syso

      - name: Build
        run: |
          go version
          ./build-release.sh "dist" "$***REMOVED***VERSION***REMOVED***"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: dist/
          retention-days: 7

  build-docker:
    runs-on: ubuntu-latest
    needs: [configure]
    env:
      VERSION: $***REMOVED******REMOVED*** needs.configure.outputs.version ***REMOVED******REMOVED***
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: docker build -t $DOCKER_IMAGE_ID .
      - name: Check
        run: |
            docker run $DOCKER_IMAGE_ID version
            docker run $DOCKER_IMAGE_ID --help
            docker run $DOCKER_IMAGE_ID help
            docker run $DOCKER_IMAGE_ID run --help
            docker run $DOCKER_IMAGE_ID inspect --help
            docker run $DOCKER_IMAGE_ID status --help
            docker run $DOCKER_IMAGE_ID stats --help
            docker run $DOCKER_IMAGE_ID scale --help
            docker run $DOCKER_IMAGE_ID pause --help
            docker run $DOCKER_IMAGE_ID resume --help

      - name: Publish
        if: $***REMOVED******REMOVED*** github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v') ***REMOVED******REMOVED***
        run: |
          VERSION="$***REMOVED***VERSION#v***REMOVED***"
          echo "Publish GHCR ($DOCKER_IMAGE_ID:$VERSION)"

          # Log into GitHub Container Registry
          echo "$***REMOVED******REMOVED*** secrets.GITHUB_TOKEN ***REMOVED******REMOVED***" | docker login https://ghcr.io -u $***REMOVED******REMOVED*** github.actor ***REMOVED******REMOVED*** --password-stdin
          docker tag "$DOCKER_IMAGE_ID" "ghcr.io/$GHCR_IMAGE_ID:$VERSION"
          docker push "ghcr.io/$GHCR_IMAGE_ID:$VERSION"
          # We also want to tag the latest stable version as latest
          if [[ "$VERSION" != "master" ]] && [[ ! "$VERSION" =~ (RC|rc) ]]; then
            echo 'Publish GHCR (latest)'
            docker tag "$DOCKER_IMAGE_ID" "ghcr.io/$GHCR_IMAGE_ID:latest"
            docker push "ghcr.io/$GHCR_IMAGE_ID:latest"
          fi

          echo "Publish Docker ($DOCKER_IMAGE_ID:$VERSION) and ($LI_DOCKER_IMAGE_ID:$VERSION)"

          # Log into Docker Hub Registry
          echo "$***REMOVED******REMOVED*** secrets.DOCKER_PASS ***REMOVED******REMOVED***" | docker login -u "$***REMOVED******REMOVED*** secrets.DOCKER_USER ***REMOVED******REMOVED***" --password-stdin
          docker tag "$DOCKER_IMAGE_ID" "$DOCKER_IMAGE_ID:$VERSION"
          docker tag "$DOCKER_IMAGE_ID" "$LI_DOCKER_IMAGE_ID:$VERSION"
          docker push "$DOCKER_IMAGE_ID:$VERSION"
          docker push "$LI_DOCKER_IMAGE_ID:$VERSION"
          # We also want to tag the latest stable version as latest
          if [[ "$VERSION" != "master" ]] && [[ ! "$VERSION" =~ (RC|rc) ]]; then
            echo 'Publish Docker (latest)'
            docker tag "$DOCKER_IMAGE_ID" "$DOCKER_IMAGE_ID:latest"
            docker tag "$DOCKER_IMAGE_ID" "$LI_DOCKER_IMAGE_ID:latest"
            docker push "$DOCKER_IMAGE_ID:latest"
            docker push "$LI_DOCKER_IMAGE_ID:latest"
          fi

  package-windows:
    runs-on: windows-2019
    defaults:
      run:
        shell: pwsh
    needs: [configure, build]
    env:
      VERSION: $***REMOVED******REMOVED*** needs.configure.outputs.version ***REMOVED******REMOVED***
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install pandoc
        uses: crazy-max/ghaction-chocolatey@b6061d587628735be315d74358228b83a7dba9a7
        with:
          args: install -y pandoc
      - name: Install wix tools
        run: |
          curl -Lso wix311-binaries.zip https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
          Expand-Archive -Path .\wix311-binaries.zip -DestinationPath .\wix311\
          echo "$pwd\wix311" | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: dist
      - name: Unzip Windows binary
        run: |
          Expand-Archive -Path ".\dist\k6-$env:VERSION-windows-amd64.zip" -DestinationPath .\packaging\
          move .\packaging\k6-$env:VERSION-windows-amd64\k6.exe .\packaging\
          rmdir .\packaging\k6-$env:VERSION-windows-amd64\
      - name: Add signtool to PATH
        run: echo "$***REMOVED***env:ProgramFiles(x86)***REMOVED***\Windows Kits\10\bin\x64" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Create the MSI package
        run: |
          $env:VERSION = $env:VERSION -replace 'v(\d+\.\d+\.\d+).*','$1'
          pandoc -s -f markdown -t rtf -o packaging\LICENSE.rtf LICENSE.md
          cd .\packaging
          candle.exe -arch x64 "-dVERSION=$env:VERSION" k6.wxs
          light.exe -ext WixUIExtension k6.wixobj

      - name: Sign Windows binary and .msi package
        # GH secrets are unavaileble when building from project forks, so this
        # will fail for external PRs, even if we wanted to do it. And we
        # don't. qWe are only only going to sign packages that are built from
        # master or a version tag, so we have enough assurance that package
        # signing works, but don't sign every PR build.
        if: $***REMOVED******REMOVED*** github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v') ***REMOVED******REMOVED***
        run: |
          # Convert base64 certificate to PFX
          $bytes = [Convert]::FromBase64String("$***REMOVED******REMOVED*** secrets.WIN_SIGN_CERT ***REMOVED******REMOVED***")
          [IO.File]::WriteAllBytes("k6.pfx", $bytes)

          # Sign the Windows binary
          signtool sign /f k6.pfx /p "$***REMOVED******REMOVED*** secrets.WIN_SIGN_PASS ***REMOVED******REMOVED***" /tr "http://timestamp.digicert.com" /td sha256 /fd sha256 "packaging\k6.exe"

          # Sign the MSI package
          signtool sign /f k6.pfx /p "$***REMOVED******REMOVED*** secrets.WIN_SIGN_PASS ***REMOVED******REMOVED***" /tr "http://timestamp.digicert.com" /td sha256 /fd sha256 "packaging\k6.msi"

          # Cleanup signing artifacts
          del k6.pfx

      - name: Rename MSI package
        # To keep it consistent with the other artifacts
        run: move "packaging\k6.msi" "packaging\k6-$env:VERSION-windows-amd64.msi"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries-windows
          path: |
            packaging/k6-*.msi
          retention-days: 7

  # Disabled until #1997 and #1998 are addressed.
  # publish-macos:
  #   runs-on: macos-latest
  #   needs: [deps, lint, test-current-cov, configure, build]
  #   if: $***REMOVED******REMOVED*** startsWith(github.ref, 'refs/tags/v') ***REMOVED******REMOVED***
  #   env:
  #     VERSION: $***REMOVED******REMOVED*** needs.configure.outputs.version ***REMOVED******REMOVED***
  #     HOMEBREW_GITHUB_API_TOKEN: $***REMOVED******REMOVED*** secrets.HOMEBREW_GITHUB_API_TOKEN ***REMOVED******REMOVED***
  #   steps:
  #     - name: Download source code archive
  #       run: curl -fsSL "$***REMOVED***GITHUB_SERVER_URL***REMOVED***/$***REMOVED***GITHUB_REPOSITORY***REMOVED***/archive/$***REMOVED***VERSION***REMOVED***.tar.gz" -o "$***REMOVED***VERSION***REMOVED***.tar.gz"
  #     - name: Set up Homebrew
  #       uses: Homebrew/actions/setup-homebrew@2eb78889a50ba021d744837934f1af2d8c4458ec
  #     - name: Create version bump PR
  #       run: |
  #         brew bump-formula-pr k6 \
  #           --url="$***REMOVED***GITHUB_SERVER_URL***REMOVED***/$***REMOVED***GITHUB_REPOSITORY***REMOVED***/archive/$***REMOVED***VERSION***REMOVED***.tar.gz" \
  #           --sha256="$(shasum -a 256 $***REMOVED***VERSION***REMOVED***.tar.gz | cut -d' ' -f1)"

  publish-github:
    runs-on: ubuntu-latest
    needs: [configure, build, package-windows]
    if: $***REMOVED******REMOVED*** startsWith(github.ref, 'refs/tags/v') ***REMOVED******REMOVED***
    env:
      VERSION: $***REMOVED******REMOVED*** needs.configure.outputs.version ***REMOVED******REMOVED***
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: dist
      - name: Download Windows binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries-windows
          path: dist
      - name: Generate checksum file
        run: cd dist && sha256sum * > "k6-$***REMOVED***VERSION***REMOVED***-checksums.txt"
      - name: Create release
        env:
          GITHUB_TOKEN: $***REMOVED******REMOVED*** secrets.GITHUB_TOKEN ***REMOVED******REMOVED***
        run: |
          set -x
          assets=()
          for asset in ./dist/*; do
            assets+=("-a" "$asset")
          done
          hub release create "$***REMOVED***assets[@]***REMOVED***" -m "$VERSION" -m "$(cat ./release\ notes/$***REMOVED***VERSION***REMOVED***.md)" "$VERSION"

  publish-packages:
    runs-on: ubuntu-latest
    needs: [configure, build, package-windows]
    if: $***REMOVED******REMOVED*** startsWith(github.ref, 'refs/tags/v') ***REMOVED******REMOVED***
    env:
      VERSION: $***REMOVED******REMOVED*** needs.configure.outputs.version ***REMOVED******REMOVED***
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: dist
      - name: Download Windows binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries-windows
          path: dist
      - name: Rename binaries
        # To be consistent with the filenames used in dl.k6.io
        run: |
          mv "dist/k6-$VERSION-windows-amd64.msi" "dist/k6-$VERSION-amd64.msi"
          mv "dist/k6-$VERSION-linux-amd64.rpm" "dist/k6-$VERSION-amd64.rpm"
          mv "dist/k6-$VERSION-linux-amd64.deb" "dist/k6-$VERSION-amd64.deb"
      - name: Setup docker-compose environment
        run: |
          cat > packaging/.env <<EOF
          AWS_ACCESS_KEY_ID=$***REMOVED******REMOVED*** secrets.AWS_ACCESS_KEY_ID ***REMOVED******REMOVED***
          AWS_SECRET_ACCESS_KEY=$***REMOVED******REMOVED*** secrets.AWS_SECRET_ACCESS_KEY ***REMOVED******REMOVED***
          AWS_DEFAULT_REGION=us-east-1
          AWS_CF_DISTRIBUTION="$***REMOVED******REMOVED*** secrets.AWS_CF_DISTRIBUTION ***REMOVED******REMOVED***"
          PGP_SIGN_KEY_PASSPHRASE=$***REMOVED******REMOVED*** secrets.PGP_SIGN_KEY_PASSPHRASE ***REMOVED******REMOVED***
          EOF
          echo "$***REMOVED******REMOVED*** secrets.PGP_SIGN_KEY ***REMOVED******REMOVED***" > packaging/sign-key.gpg
      - name: Publish packages
        run: |
          echo "$***REMOVED******REMOVED*** secrets.GITHUB_TOKEN ***REMOVED******REMOVED***" | docker login https://ghcr.io -u $***REMOVED******REMOVED*** github.actor ***REMOVED******REMOVED*** --password-stdin
          cd packaging
          docker-compose pull packager
          docker-compose run --rm packager
