name: Build
on:
  workflow_dispatch:
    inputs:
      k6_version:
        description: 'The version of the release, it must use the semantic versioning format with the v prefix. It is a development release so it is suggested to append a build metadata (e.g. v0.38.0-dev).'
        required: true
      go_version:
        description: 'Go version for building binaries'
        default: '1.x'
        required: true
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

defaults:
  run:
    shell: bash

env:
  APP_NAME: "k6"
  # We'll push to two DockerHub repos at once; `loadimpact/k6` repo is required for backwards compatibility
  LI_DOCKER_IMAGE_ID: "loadimpact/k6"
  DOCKER_IMAGE_ID: "grafana/k6"
  GHCR_IMAGE_ID: $***REMOVED******REMOVED*** github.repository ***REMOVED******REMOVED***
  DEFAULT_GO_VERSION: "1.18.x"

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      k6_version: $***REMOVED******REMOVED*** steps.get_k6_version.outputs.k6_version ***REMOVED******REMOVED***
      go_version: $***REMOVED******REMOVED*** steps.get_go_version.outputs.go_version ***REMOVED******REMOVED***
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get the k6 version
        id: get_k6_version
        run: |
          set -x # Show exactly what commands are executed
          if [[ "$***REMOVED******REMOVED*** github.event_name ***REMOVED******REMOVED***" == "workflow_dispatch" ]] && [[ "$***REMOVED******REMOVED*** github.event.inputs.k6_version ***REMOVED******REMOVED***" != "" ]]; then
            VERSION="$***REMOVED******REMOVED*** github.event.inputs.k6_version ***REMOVED******REMOVED***"
            echo "Building custom dev build with version '$***REMOVED***VERSION***REMOVED***' from manual workflow_dispatch..."
          elif [[ "$***REMOVED***GITHUB_REF***REMOVED***" =~ ^refs/tags/v.+$ ]]; then
            VERSION="$***REMOVED***GITHUB_REF##*/***REMOVED***"
            echo "Building real version tag '$***REMOVED***GITHUB_REF***REMOVED***', parsed '$***REMOVED***VERSION***REMOVED***' as the actual version..."
          else
            VERSION="$(git describe --tags --always --long --dirty)"
            echo "Building a non-version ref '$***REMOVED***GITHUB_REF***REMOVED***', use '$***REMOVED***VERSION***REMOVED***' as the version instead..."
          fi
          echo "VERSION=$***REMOVED***VERSION***REMOVED***"
          echo "::set-output name=k6_version::$***REMOVED***VERSION***REMOVED***"
      - name: Get the used Go version
        id: get_go_version
        run: |
          set -x # Show exactly what commands are executed
          if [[ "$***REMOVED******REMOVED*** github.event_name ***REMOVED******REMOVED***" == "workflow_dispatch" ]] && [[ "$***REMOVED******REMOVED*** github.event.inputs.go_version ***REMOVED******REMOVED***" != "" ]]; then
            GO_VERSION="$***REMOVED******REMOVED*** github.event.inputs.go_version ***REMOVED******REMOVED***"
            echo "Using custom Go version '$***REMOVED***GO_VERSION***REMOVED***' from manual workflow_dispatch..."
          else
            GO_VERSION="$***REMOVED***DEFAULT_GO_VERSION***REMOVED***"
            echo "Using the default Go version '$***REMOVED***GO_VERSION***REMOVED***'..."
          fi
          echo "GO_VERSION=$***REMOVED***GO_VERSION***REMOVED***"
          echo "::set-output name=go_version::$***REMOVED***GO_VERSION***REMOVED***"

  build:
    runs-on: ubuntu-latest
    needs: [configure]
    env:
      VERSION: $***REMOVED******REMOVED*** needs.configure.outputs.k6_version ***REMOVED******REMOVED***
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: $***REMOVED******REMOVED*** needs.configure.outputs.go_version ***REMOVED******REMOVED***
      - name: Install nfpm (dep and rpm package builder)
        run: |
          go install github.com/goreleaser/nfpm/v2/cmd/nfpm@v2.16.0
      - name: Install goversioninfo (.syso file creator)
        run: |
          go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@v1.4.0
      - name: Generate Windows binary metadata (.syso files)
        run: |
          IFS=. read -a version_parts <<< "$***REMOVED***VERSION#v***REMOVED***"
          IFS=- read -a version_patch <<< "$***REMOVED***version_parts[2]***REMOVED***"

          # Need a blank versioninfo.json for the CLI overrides to work.
          echo '***REMOVED******REMOVED***' > versioninfo.json
          set -x
          goversioninfo -64 \
            -platform-specific=true \
            -charset="1200" \
            -company="Raintank Inc. d.b.a. Grafana Labs" \
            -copyright="© Raintank Inc. d.b.a. Grafana Labs. Licensed under AGPL." \
            -description="A modern load testing tool, using Go and JavaScript" \
            -icon=packaging/k6.ico \
            -internal-name="k6" \
            -original-name="k6.exe" \
            -product-name="k6" \
            -translation="0x0409" \
            -ver-major="$***REMOVED***version_parts[0]***REMOVED***" \
            -ver-minor="$***REMOVED***version_parts[1]***REMOVED***" \
            -ver-patch="$***REMOVED***version_patch[0]***REMOVED***" \
            -special-build=$(IFS='-'; echo "$***REMOVED***version_patch[*]:1***REMOVED***";) \
            -product-version="$***REMOVED***VERSION#v***REMOVED***"

          set +x
          ls -lah | grep -i syso

      - name: Build
        run: |
          go version
          ./build-release.sh "dist" "$***REMOVED***VERSION***REMOVED***"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: dist/
          retention-days: 7

  build-docker:
    runs-on: ubuntu-latest
    needs: [configure]
    env:
      VERSION: $***REMOVED******REMOVED*** needs.configure.outputs.k6_version ***REMOVED******REMOVED***
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: docker build -t $DOCKER_IMAGE_ID .
      - name: Check
        run: |
            docker run $DOCKER_IMAGE_ID version
            docker run $DOCKER_IMAGE_ID --help
            docker run $DOCKER_IMAGE_ID help
            docker run $DOCKER_IMAGE_ID run --help
            docker run $DOCKER_IMAGE_ID inspect --help
            docker run $DOCKER_IMAGE_ID status --help
            docker run $DOCKER_IMAGE_ID stats --help
            docker run $DOCKER_IMAGE_ID scale --help
            docker run $DOCKER_IMAGE_ID pause --help
            docker run $DOCKER_IMAGE_ID resume --help

      - name: Publish
        if: $***REMOVED******REMOVED*** github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v') ***REMOVED******REMOVED***
        run: |
          VERSION="$***REMOVED***VERSION#v***REMOVED***"
          echo "Publish GHCR ($DOCKER_IMAGE_ID:$VERSION)"

          # Log into GitHub Container Registry
          echo "$***REMOVED******REMOVED*** secrets.GITHUB_TOKEN ***REMOVED******REMOVED***" | docker login https://ghcr.io -u $***REMOVED******REMOVED*** github.actor ***REMOVED******REMOVED*** --password-stdin
          docker tag "$DOCKER_IMAGE_ID" "ghcr.io/$GHCR_IMAGE_ID:$VERSION"
          docker push "ghcr.io/$GHCR_IMAGE_ID:$VERSION"
          # We also want to tag the latest stable version as latest
          if [[ "$VERSION" != "master" ]] && [[ ! "$VERSION" =~ (RC|rc) ]]; then
            echo 'Publish GHCR (latest)'
            docker tag "$DOCKER_IMAGE_ID" "ghcr.io/$GHCR_IMAGE_ID:latest"
            docker push "ghcr.io/$GHCR_IMAGE_ID:latest"
          fi

          echo "Publish Docker ($DOCKER_IMAGE_ID:$VERSION) and ($LI_DOCKER_IMAGE_ID:$VERSION)"

          # Log into Docker Hub Registry
          echo "$***REMOVED******REMOVED*** secrets.DOCKER_PASS ***REMOVED******REMOVED***" | docker login -u "$***REMOVED******REMOVED*** secrets.DOCKER_USER ***REMOVED******REMOVED***" --password-stdin
          docker tag "$DOCKER_IMAGE_ID" "$DOCKER_IMAGE_ID:$VERSION"
          docker tag "$DOCKER_IMAGE_ID" "$LI_DOCKER_IMAGE_ID:$VERSION"
          docker push "$DOCKER_IMAGE_ID:$VERSION"
          docker push "$LI_DOCKER_IMAGE_ID:$VERSION"
          # We also want to tag the latest stable version as latest
          if [[ "$VERSION" != "master" ]] && [[ ! "$VERSION" =~ (RC|rc) ]]; then
            echo 'Publish Docker (latest)'
            docker tag "$DOCKER_IMAGE_ID" "$DOCKER_IMAGE_ID:latest"
            docker tag "$DOCKER_IMAGE_ID" "$LI_DOCKER_IMAGE_ID:latest"
            docker push "$DOCKER_IMAGE_ID:latest"
            docker push "$LI_DOCKER_IMAGE_ID:latest"
          fi

  package-windows:
    runs-on: windows-2019
    defaults:
      run:
        shell: pwsh
    needs: [configure, build]
    env:
      VERSION: $***REMOVED******REMOVED*** needs.configure.outputs.k6_version ***REMOVED******REMOVED***
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install pandoc
        uses: crazy-max/ghaction-chocolatey@b6061d587628735be315d74358228b83a7dba9a7
        with:
          args: install -y pandoc
      - name: Install wix tools
        run: |
          curl -Lso wix311-binaries.zip https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
          Expand-Archive -Path .\wix311-binaries.zip -DestinationPath .\wix311\
          echo "$pwd\wix311" | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: dist
      - name: Unzip Windows binary
        run: |
          Expand-Archive -Path ".\dist\k6-$env:VERSION-windows-amd64.zip" -DestinationPath .\packaging\
          move .\packaging\k6-$env:VERSION-windows-amd64\k6.exe .\packaging\
          rmdir .\packaging\k6-$env:VERSION-windows-amd64\
      - name: Add signtool to PATH
        run: echo "$***REMOVED***env:ProgramFiles(x86)***REMOVED***\Windows Kits\10\bin\x64" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Create the MSI package
        run: |
          $env:VERSION = $env:VERSION -replace 'v(\d+\.\d+\.\d+).*','$1'
          pandoc -s -f markdown -t rtf -o packaging\LICENSE.rtf LICENSE.md
          cd .\packaging
          candle.exe -arch x64 "-dVERSION=$env:VERSION" k6.wxs
          light.exe -ext WixUIExtension k6.wixobj

      - name: Sign Windows binary and .msi package
        # GH secrets are unavaileble when building from project forks, so this
        # will fail for external PRs, even if we wanted to do it. And we don't.
        # We are only going to sign packages that are built from master or a
        # version tag, or manually triggered dev builds, so we have enough
        # assurance that package signing works, but don't sign every PR build.
        if: $***REMOVED******REMOVED*** github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch' ***REMOVED******REMOVED***
        run: |
          # Convert base64 certificate to PFX
          $bytes = [Convert]::FromBase64String("$***REMOVED******REMOVED*** secrets.WIN_SIGN_CERT ***REMOVED******REMOVED***")
          [IO.File]::WriteAllBytes("k6.pfx", $bytes)

          # Sign the Windows binary
          signtool sign /f k6.pfx /p "$***REMOVED******REMOVED*** secrets.WIN_SIGN_PASS ***REMOVED******REMOVED***" /tr "http://timestamp.digicert.com" /td sha256 /fd sha256 "packaging\k6.exe"

          # Sign the MSI package
          signtool sign /f k6.pfx /p "$***REMOVED******REMOVED*** secrets.WIN_SIGN_PASS ***REMOVED******REMOVED***" /tr "http://timestamp.digicert.com" /td sha256 /fd sha256 "packaging\k6.msi"

          # Cleanup signing artifacts
          del k6.pfx

      - name: Rename MSI package
        # To keep it consistent with the other artifacts
        run: move "packaging\k6.msi" "packaging\k6-$env:VERSION-windows-amd64.msi"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries-windows
          path: |
            packaging/k6-*.msi
          retention-days: 7

  # Disabled until #1997 and #1998 are addressed.
  # publish-macos:
  #   runs-on: macos-latest
  #   needs: [configure, build]
  #   if: $***REMOVED******REMOVED*** startsWith(github.ref, 'refs/tags/v') && github.event_name != 'workflow_dispatch' ***REMOVED******REMOVED***
  #   env:
  #     VERSION: $***REMOVED******REMOVED*** needs.configure.outputs.k6_version ***REMOVED******REMOVED***
  #     HOMEBREW_GITHUB_API_TOKEN: $***REMOVED******REMOVED*** secrets.HOMEBREW_GITHUB_API_TOKEN ***REMOVED******REMOVED***
  #   steps:
  #     - name: Download source code archive
  #       run: curl -fsSL "$***REMOVED***GITHUB_SERVER_URL***REMOVED***/$***REMOVED***GITHUB_REPOSITORY***REMOVED***/archive/$***REMOVED***VERSION***REMOVED***.tar.gz" -o "$***REMOVED***VERSION***REMOVED***.tar.gz"
  #     - name: Set up Homebrew
  #       uses: Homebrew/actions/setup-homebrew@2eb78889a50ba021d744837934f1af2d8c4458ec
  #     - name: Create version bump PR
  #       run: |
  #         brew bump-formula-pr k6 \
  #           --url="$***REMOVED***GITHUB_SERVER_URL***REMOVED***/$***REMOVED***GITHUB_REPOSITORY***REMOVED***/archive/$***REMOVED***VERSION***REMOVED***.tar.gz" \
  #           --sha256="$(shasum -a 256 $***REMOVED***VERSION***REMOVED***.tar.gz | cut -d' ' -f1)"

  publish-github:
    runs-on: ubuntu-latest
    needs: [configure, build, package-windows]
    if: $***REMOVED******REMOVED*** startsWith(github.ref, 'refs/tags/v') && github.event_name != 'workflow_dispatch' ***REMOVED******REMOVED***
    env:
      VERSION: $***REMOVED******REMOVED*** needs.configure.outputs.k6_version ***REMOVED******REMOVED***
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: dist
      - name: Download Windows binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries-windows
          path: dist
      - name: Generate checksum file
        run: cd dist && sha256sum * > "k6-$***REMOVED***VERSION***REMOVED***-checksums.txt"
      - name: Create release
        env:
          GITHUB_TOKEN: $***REMOVED******REMOVED*** secrets.GITHUB_TOKEN ***REMOVED******REMOVED***
        run: |
          set -x
          assets=()
          for asset in ./dist/*; do
            assets+=("-a" "$asset")
          done
          hub release create "$***REMOVED***assets[@]***REMOVED***" -m "$VERSION" -m "$(cat ./release\ notes/$***REMOVED***VERSION***REMOVED***.md)" "$VERSION"

  publish-packages:
    runs-on: ubuntu-latest
    needs: [configure, build, package-windows]
    if: $***REMOVED******REMOVED*** startsWith(github.ref, 'refs/tags/v') && github.event_name != 'workflow_dispatch' ***REMOVED******REMOVED***
    env:
      VERSION: $***REMOVED******REMOVED*** needs.configure.outputs.k6_version ***REMOVED******REMOVED***
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: dist
      - name: Download Windows binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries-windows
          path: dist
      - name: Rename binaries
        # To be consistent with the filenames used in dl.k6.io
        run: |
          mv "dist/k6-$VERSION-windows-amd64.msi" "dist/k6-$VERSION-amd64.msi"
          mv "dist/k6-$VERSION-linux-amd64.rpm" "dist/k6-$VERSION-amd64.rpm"
          mv "dist/k6-$VERSION-linux-amd64.deb" "dist/k6-$VERSION-amd64.deb"
      - name: Setup docker-compose environment
        run: |
          cat > packaging/.env <<EOF
          AWS_ACCESS_KEY_ID=$***REMOVED******REMOVED*** secrets.AWS_ACCESS_KEY_ID ***REMOVED******REMOVED***
          AWS_SECRET_ACCESS_KEY=$***REMOVED******REMOVED*** secrets.AWS_SECRET_ACCESS_KEY ***REMOVED******REMOVED***
          AWS_DEFAULT_REGION=us-east-1
          AWS_CF_DISTRIBUTION="$***REMOVED******REMOVED*** secrets.AWS_CF_DISTRIBUTION ***REMOVED******REMOVED***"
          PGP_SIGN_KEY_PASSPHRASE=$***REMOVED******REMOVED*** secrets.PGP_SIGN_KEY_PASSPHRASE ***REMOVED******REMOVED***
          EOF
          echo "$***REMOVED******REMOVED*** secrets.PGP_SIGN_KEY ***REMOVED******REMOVED***" > packaging/sign-key.gpg
      - name: Publish packages
        run: |
          echo "$***REMOVED******REMOVED*** secrets.GITHUB_TOKEN ***REMOVED******REMOVED***" | docker login https://ghcr.io -u $***REMOVED******REMOVED*** github.actor ***REMOVED******REMOVED*** --password-stdin
          cd packaging
          docker-compose pull packager
          docker-compose run --rm packager
