// go generate
// generated by js/modules/k6/html/gen/main.go directed by js/modules/k6/html/elements.go;  DO NOT EDIT
package html
func selToElement(sel Selection) goja.Value ***REMOVED***
	if sel.sel.Length() == 0 ***REMOVED***
		return goja.Undefined()
	***REMOVED***

	elem := Element***REMOVED***sel.sel.Nodes[0], &sel***REMOVED***
	
	switch elem.node.Data ***REMOVED***  
	case AnchorTagName:
		return sel.rt.ToValue(AnchorElement***REMOVED***HrefElement***REMOVED***elem***REMOVED******REMOVED***)
	 
	case AreaTagName:
		return sel.rt.ToValue(AreaElement***REMOVED***HrefElement***REMOVED***elem***REMOVED******REMOVED***)
	 
	case BaseTagName:
		return sel.rt.ToValue(BaseElement***REMOVED***elem***REMOVED***)
	 
	case ButtonTagName:
		return sel.rt.ToValue(ButtonElement***REMOVED***elem***REMOVED***)
	 
	default:
		return sel.rt.ToValue(elem)
	***REMOVED***
***REMOVED***

 
func (e HrefElement) Rel() string ***REMOVED***
	return e.attrAsString("rel")
***REMOVED***
 
func (e AreaElement) Href() string ***REMOVED***
	return e.attrAsString("href")
***REMOVED***
 
func (e AreaElement) AccessKey() bool ***REMOVED***
	return e.attrIsPresent("accesskey")
***REMOVED***
 
func (e BaseElement) Autofocus() string ***REMOVED***
	return e.attrAsString("autofocus")
***REMOVED***
 
func (e ButtonElement) AccessKey() string ***REMOVED***
	return e.attrAsString("accesskey")
***REMOVED***
 
func (e ButtonElement) Autofocus() string ***REMOVED***
	return e.attrAsString("autofocus")
***REMOVED***
 
func (e ButtonElement) Disabled() string ***REMOVED***
	return e.attrAsString("disabled")
***REMOVED***

